### ISSUE TITLE
Low time out values for libnetcdf 4.6.1

### ISSUE THREAD

**Issue by ocefpaf** [AnacondaRecipes/libnetcdf-feedstock#5]
@msarahan and @mingwandroid latest netcdf has a really low timeout value and that is causing a lot of pain to users, see https://github.com/Unidata/netcdf4-python/issues/836#issuecomment-417187942 for more info.

While we wait for a fix upstream I increased the timeout value for the conda-forge package in https://github.com/conda-forge/libnetcdf-feedstock/pull/53.

It would be nice to have the same fix here b/c a lot of our scientists are using `defaults` exclusively due to the channel mixing problems.

**Comment by jjhelmus** [comment]
Thanks for the heads up @ocefpaf , I'll pull this patch into out builds of libnetcdf4 today.

**Comment by jjhelmus** [comment]
Packages with this patch are now available in `defaults` with as build `1`.

**Comment by ocefpaf** [comment]
Thanks! We can probably drop the patch in the next release. I'll keep you posted.
